### ISSUE TITLE
作为console插件使用时自动导入脚本

### ISSUE THREAD

**Issue by Miaow233** [only52607/lua-mirai#49]
启动时自动导入&启用脚本

两种思路：
1. 在config目录下创建配置文件，记录脚本路径及启用状态

setting.yml
```yml
scripts:
  -
     path: /home/mirai/test1.lua
     enable: true
  -
     path: /home/mirai/test2.lua
     enable: false
```

2. 仿照 `miraiAndroid` 的脚本导入功能，在 `data/com.ooooonly.luaMirai/` 目录下创建脚本文件夹，自动导入文件夹内所有文件

```
.
├── bots
├── config
│   ├── com.ooooonly.luaMirai
│   │   └── setting.yml
│   ├── Console
│   │   ├── Command.yml
│   │   └── PermissionService.yml
│   └── net.mamoe.mirai-api-http
│       └── setting.yml
├── data
│   ├── com.ooooonly.luaMirai
│   │   ├── data
│   │   └── scripts
│   └── net.mamoe.mirai-api-http
│       ├── images
│       └── voices
```
